blank_issues_enabled: false
contact_links:
  - name: Contributing guide
    url: https://github.com/zachway/spectra_pointer/blob/main/CONTRIBUTING.md
    about: How to report bugs, add an archive, or submit a pull request.
