"""Hand-maintained per-(archive, instrument) resolving power, plus the parser
that turns its display strings into numeric ranges -- pulled out of
webapp.app for the same reason as webapp/instrument_wavelengths.py (see that
module's docstring): scripts/export_to_parquet.py needs them too, to sort
instruments into the CMD page's resolution presets, and can't import
webapp.app itself. No side effects, no Flask/DB imports.
"""

from __future__ import annotations

import re

# Resolving power (R = lambda/delta-lambda) per (archive display_name,
# instrument) -- like webapp.app's NOT_YET_TRACKED, this can't be derived from the
# database (holdings don't carry it) so it's hand-maintained from each
# instrument's published specs. Keyed by (display_name, instrument) rather
# than instrument name alone because a few names collide across archives
# (e.g. "OSIRIS" is a different instrument at Keck vs. GTC). Many real
# spectrographs offer several gratings/modes with different R -- shown as a
# range where that's the common case rather than picking one mode
# arbitrarily. "n/a" marks instruments that are primarily imagers with no
# (or only a fixed low-R grism) spectroscopic mode; "—" marks instruments
# not yet looked up, mostly retired/obscure ones lacking an easily
# confirmed spec.
INSTRUMENT_RESOLVING_POWER: dict[tuple[str, str], str] = {
    ('Asiago Observatory (Echelle)', 'Echelle + Andor iKon DW436-BV'): 'R ≈ 20,000',
    ('Asiago Observatory (Echelle)', 'echelle hi-res Spectrograph'): 'R ≈ 20,000',
    ('Asiago Observatory (Echelle)', 'Echelle Hi-Res Spectrograph'): 'R ≈ 20,000',
    ('Asiago Observatory (Echelle)', 'ECHELLE REOSC'): 'R ≈ 20,000',
    ('CARMENES', 'CARMENES VIS'): 'R ≈ 94,600',
    ('CARMENES (CAHA archive, VIS+NIR)', 'CARMENES NIR'): 'R ≈ 80,600',
    ('CARMENES (CAHA archive, VIS+NIR)', 'CARMENES VIS'): 'R ≈ 94,600',
    # Same physical instrument as the two CARMENES entries above -- these are
    # just different derived data products (a co-added telluric-corrected
    # template library and a fixed input catalog snapshot) over the same
    # CAHA-hosted VIS/NIR channels, so the R doesn't change.
    ('CARMENES Telluric-Corrected Template Library', 'CARMENES VIS'): 'R ≈ 94,600',
    ('CARMENES Telluric-Corrected Template Library', 'CARMENES NIR'): 'R ≈ 80,600',
    ('CARMENES Reiners et al. 2018 Input Catalog', 'CARMENES VIS'): 'R ≈ 94,600',
    ('CARMENES Reiners et al. 2018 Input Catalog', 'CARMENES NIR'): 'R ≈ 80,600',
    ('CFHT / CADC', 'SPIRou'): 'R ≈ 70,000',
    ('CFHT / CADC', 'ESPaDOnS'): 'R ≈ 68,000 (spectroscopy mode)',
    ('CFHT / CADC', 'MegaPrime'): 'n/a (wide-field imager)',
    ('CFHT / CADC', 'UH8K'): 'n/a (imaging mosaic camera)',
    ('CFHT / CADC', 'HRCAM'): 'n/a (imaging camera)',
    ('CFHT / CADC', 'FTS'): 'R ≈ 100,000+ (Fourier Transform Spectrometer, variable)',
    ('CFHT / CADC', 'GECKO'): 'R ≈ 120,000 (fiber-fed echelle)',
    ('CFHT / CADC', 'TIGER'): 'R ≈ 1,600–3,600 (integral-field, grism-dependent)',
    ('CFHT / CADC', 'MOS'): 'R ≈ 400–3,000 (grism-dependent, retired)',
    ('CFHT / CADC', 'SIS'): 'R ≈ 400–3,000 (grism-dependent, retired)',
    ('CFHT / CADC', 'OSIS'): '—',
    ('CFHT / CADC', 'PUMA'): '—',
    ('CFHT / CADC', 'SISFP'): '—',
    ('CFHT / CADC', 'HERZBERG'): '—',
    ('CFHT / CADC', 'ISIS'): '—',
    ('CFHT / CADC', 'PYTHIAS'): '—',
    ('DAO (Dominion Astrophysical Observatory)', 'McKellar Spectrograph'): 'R ≈ 10,000–20,000 (grating-dependent)',
    ('DAO (Dominion Astrophysical Observatory)', 'Cassegrain Spectrograph'): 'R ≈ 1,000–12,000 (grating-dependent)',
    ('DAO (Dominion Astrophysical Observatory)', 'Cassegrain Spectropolarimeter'): 'R ≈ 1,000–5,000 (grating-dependent)',
    ('DAO (Dominion Astrophysical Observatory)', 'Radial-Velocity Scanner'): '—',
    ('DESI', 'DESI'): 'R ≈ 2,000–5,500 (wavelength-dependent)',
    ('ELODIE (OHP)', 'ELODIE'): 'R ≈ 42,000',
    ('ESO Science Archive', 'GIRAFFE'): 'R ≈ 6,000–30,000 (mode-dependent)',
    ('ESO Science Archive', 'HARPS'): 'R ≈ 115,000',
    ('ESO Science Archive', 'XSHOOTER'): 'R ≈ 3,000–17,000 (arm/slit-dependent)',
    ('ESO Science Archive', 'VIMOS'): 'R ≈ 200–2,500 (grism-dependent)',
    ('ESO Science Archive', 'FORS2'): 'R ≈ 260–2,600 (grism-dependent)',
    ('ESO Science Archive', 'UVES'): 'R ≈ 40,000–110,000 (slit-dependent)',
    ('ESO Science Archive', 'FEROS'): 'R ≈ 48,000',
    ('ESO Science Archive', 'NIRPS'): 'R ≈ 100,000',
    ('ESO Science Archive', 'ESPRESSO'): 'R ≈ 70,000–190,000 (mode-dependent)',
    ('ESO Science Archive', 'EFOSC'): 'R ≈ 600–2,500 (grism-dependent)',
    ('ESO Science Archive', 'KMOS'): 'R ≈ 1,500–4,000 (grating-dependent)',
    ('ESO Science Archive', 'CRIRES'): 'R ≈ 50,000–100,000+ (slit-dependent)',
    ('ESO Science Archive', 'SOFI'): 'R ≈ 600–1,800 (grism-dependent)',
    ('ESO Science Archive', 'APEXHET'): '—',
    ('ESO Science Archive', 'FORS1'): 'R ≈ 260–2,600 (grism-dependent, retired)',
    ('ESO Science Archive', ''): '—',
    ('ESO Science Archive', 'MUSE'): 'R ≈ 1,700–4,000',
    ('ESO Science Archive', 'SINFONI'): 'R ≈ 1,500–4,000 (grating-dependent)',
    # Raw-archive counterparts to the ESO Science Archive entries above --
    # same physical instrument, same resolving power, whether the spectrum
    # is a Phase 3 reduced product or straight off the telescope. Only the
    # instruments already vetted above are repeated here; VISIR, CES, EMMI,
    # GRAVITY, SPHERE, NAOS+CONICA, TIMMI2, ISAAC, ERIS, SOXS, and SHOOT are
    # real spectrographs in the raw data too but left out rather than
    # guessed at, same graceful-degradation convention as elsewhere in this
    # dict -- a missing key just means that instrument's bar doesn't render.
    ('ESO Archive (Raw)', 'HARPS'): 'R ≈ 115,000',
    ('ESO Archive (Raw)', 'XSHOOTER'): 'R ≈ 3,000–17,000 (arm/slit-dependent)',
    ('ESO Archive (Raw)', 'FORS2'): 'R ≈ 260–2,600 (grism-dependent)',
    ('ESO Archive (Raw)', 'FORS1'): 'R ≈ 260–2,600 (grism-dependent, retired)',
    ('ESO Archive (Raw)', 'UVES'): 'R ≈ 40,000–110,000 (slit-dependent)',
    ('ESO Archive (Raw)', 'FEROS'): 'R ≈ 48,000',
    ('ESO Archive (Raw)', 'NIRPS'): 'R ≈ 100,000',
    ('ESO Archive (Raw)', 'ESPRESSO'): 'R ≈ 70,000–190,000 (mode-dependent)',
    ('ESO Archive (Raw)', 'EFOSC'): 'R ≈ 600–2,500 (grism-dependent)',
    ('ESO Archive (Raw)', 'CRIRES'): 'R ≈ 50,000–100,000+ (slit-dependent)',
    ('ESO Archive (Raw)', 'SOFI'): 'R ≈ 600–1,800 (grism-dependent)',
    ('FEROS Public Spectra (GAVO)', 'FEROS'): 'R ≈ 48,000',
    ('Flash/Heros Public Spectra (GAVO)', 'Flash/Heros'): 'R ≈ 20,000',
    ('GALAH', 'GALAH (HERMES)'): 'R ≈ 28,000',
    ('GTC (Gran Telescopio CANARIAS)', 'EMIR'): 'R ≈ 4,000–5,000 (MOS mode)',
    ('GTC (Gran Telescopio CANARIAS)', 'OSIRIS'): 'R ≈ 300–2,500 (grism-dependent)',
    ('GTC (Gran Telescopio CANARIAS)', 'MEGARA'): 'R ≈ 6,000–20,000 (LR/MR/HR modes)',
    ('GTC (Gran Telescopio CANARIAS)', 'HORuS'): 'R ≈ 25,000',
    ('GTC (Gran Telescopio CANARIAS)', 'CANARICAM'): 'R ≈ 175–1,300 (mode-dependent)',
    ('Gaia RVS', 'Gaia RVS'): 'R ≈ 11,500',
    ('Gemini Observatory Archive', 'GNIRS'): 'R ≈ 500–18,000 (mode-dependent)',
    ('Gemini Observatory Archive', 'GMOS-N'): 'R ≈ 400–5,000 (grating-dependent)',
    ('Gemini Observatory Archive', 'GMOS-S'): 'R ≈ 400–5,000 (grating-dependent)',
    ('Gemini Observatory Archive', 'PHOENIX'): 'R ≈ 50,000',
    ('Gemini Observatory Archive', 'GPI'): 'R ≈ 35–90 (IFS mode)',
    ('Gemini Observatory Archive', 'NIRI'): 'R ≈ 500–1,300 (grism mode)',
    ('Gemini Observatory Archive', 'NIFS'): 'R ≈ 5,290',
    ('Gemini Observatory Archive', 'F2'): 'R ≈ 900–3,600 (grating-dependent)',
    ('Gemini Observatory Archive', 'GRACES'): 'R ≈ 40,000–67,500 (mode-dependent)',
    ('Gemini Observatory Archive', 'MAROON-X'): 'R ≈ 85,000',
    ('Gemini Observatory Archive', 'michelle'): 'R ≈ up to 30,000 (echelle mode, retired)',
    ('Gemini Observatory Archive', 'TEXES'): 'R ≈ up to 100,000',
    ('Gemini Observatory Archive', 'TReCS'): 'R ≈ 100–1,000 (retired)',
    ('Gemini Observatory Archive', 'GHOST'): 'R ≈ 50,000 / 75,000 (standard/high-res mode)',
    ('Gemini Observatory Archive', 'FLAMINGOS'): 'R ≈ 1,300 (low-res, retired)',
    ('Gemini Observatory Archive', 'CIRPASS'): '—',
    ('Gemini Observatory Archive', 'bHROS'): 'R ≈ 150,000 (retired)',
    ('Gemini Observatory Archive', 'OSCIR'): '—',
    ('Gemini Observatory Archive — GHOST', 'GHOST'): 'R ≈ 50,000 / 75,000 (standard/high-res mode)',
    ('Gemini Observatory Archive — IGRINS', 'IGRINS'): 'R ≈ 45,000',
    ('HARPS-N (TNG)', 'HARPS-N'): 'R ≈ 115,000',
    ('HERMES (Mercator Telescope, KU Leuven)', 'HERMES'): 'R ≈ 25,000–86,000 (mode-dependent)',
    ('HEROS at Ondrejov', 'HEROS (Ondrejov)'): 'R ≈ 20,000',
    ('HPOL (Wisconsin H-alpha/HPOL spectropolarimeter, STScI)', 'HPOL'): 'R ≈ 130–1,050 (era/channel-dependent; Reticon 1989-94, CCD 1995+)',
    ('IACOB Spectroscopic Database (IAC)', 'MERCATOR'): 'R ≈ 85,000',
    ('IACOB Spectroscopic Database (IAC)', 'NOT'): 'R ≈ 25,000–67,000 (FIES mode-dependent)',
    ('ING Archive (WHT/ISIS)', 'WHT/ISIS red arm'): 'R ≈ 600–8,000 (grating-dependent)',
    ('ING Archive (WHT/ISIS)', 'WHT/ISIS blue arm'): 'R ≈ 600–8,000 (grating-dependent)',
    ('ING Archive (WHT/ISIS)', 'WHT/ISIS RED ARM'): 'R ≈ 600–8,000 (grating-dependent)',
    ('ING Archive (WHT/ISIS)', 'WHT/ISIS BLUE ARM'): 'R ≈ 600–8,000 (grating-dependent)',
    ('Spitzer Heritage Archive (IRS + MIPS-SED)', 'Spitzer/IRS (Stare)'): 'R ≈ 60–130 (SL/LL) or R ≈ 600 (SH/LH), by module',
    ('Spitzer Heritage Archive (IRS + MIPS-SED)', 'Spitzer/IRS (Map)'): 'R ≈ 60–130 (SL/LL) or R ≈ 600 (SH/LH), by module',
    ('Spitzer Heritage Archive (IRS + MIPS-SED)', 'Spitzer/MIPS-SED'): 'R ≈ 15–25 (low-res SED mode)',
    ('IRSA Space-Mission Stellar Collections', 'Spitzer/IRS (SASS)'): 'R ≈ 60–130 (SL/LL low-res modules)',
    ('IRSA Space-Mission Stellar Collections', 'Spitzer/IRS (Std Stars)'): 'R ≈ 60–130 (SL/LL low-res modules)',
    ('IRSA Space-Mission Stellar Collections', 'Spitzer/IRS (FEPS)'): 'R ≈ 60–130 (SL/LL low-res modules)',
    ('IRSA Space-Mission Stellar Collections', 'Spitzer/IRS (FEPS high-res)'): 'R ≈ 600 (SH/LH high-res modules)',
    ('IRSA Space-Mission Stellar Collections', 'Spitzer/IRS (Disks SH)'): 'R ≈ 600 (SH high-res module)',
    ('IRSA Space-Mission Stellar Collections', 'Spitzer/IRS (c2d)'): 'R ≈ 60–130 (SL/LL low-res) + R ≈ 600 (SH/LH)',
    ('IRSA Space-Mission Stellar Collections', 'ISO/SWS'): 'R ≈ 1,000–2,500 (grating mode)',
    ('IRSA Space-Mission Stellar Collections', 'IRAS/LRS'): 'R ≈ 20–60',
    ('IRSA Space-Mission Stellar Collections', 'SOFIA/EXES'): 'R ≈ 3,000–100,000 (mode-dependent)',
    ('IRSA Space-Mission Stellar Collections', 'IRTF/MEarth'): 'R ≈ 200 (prism) – 2,500 (cross-dispersed)',
    ('IRSA Space-Mission Stellar Collections', 'SOFIA/FLITECAM'): 'R ≈ 1,100–1,300 (grism)',
    ('IRSA Space-Mission Stellar Collections', 'SOFIA/FORCAST'): 'R ≈ 110–260 (grism), ≈ 1,200 cross-dispersed',
    ('IRSA Space-Mission Stellar Collections', 'Herschel/HIFI (HIFISTARS)'): 'R ≈ 10,000,000 (heterodyne)',
    ('IRSA Space-Mission Stellar Collections', 'ISO/SWS (Atlas)'): 'R ≈ 1,000–2,500 (grating mode)',
    ('IRSA Space-Mission Stellar Collections', 'CTIO Blanco/Hydra (BRAVA)'): 'R ≈ 4,200',
    ('Fesenkov Astrophysical Institute (Kazakhstan VO)', 'TCO eShel'): 'R ≈ 7,400–8,400',
    ('Fesenkov Astrophysical Institute (Kazakhstan VO)', 'FAI AZT-8 (PN archive)'): 'R ≈ 1,300–23,000 (setup-dependent)',
    ('NOVA (Argentine Virtual Observatory)', 'FIRE-LCO'): 'R ≈ 6,000 (echelle)',
    ('NOVA (Argentine Virtual Observatory)', 'GNIRS-GEMINI'): 'R ≈ 500–18,000 (mode-dependent)',
    ('IRTF SpeX (via IRSA)', 'SpeX'): 'R ≈ 200 (prism) – 2,500 (cross-dispersed)',
    ('IRTF iSHELL (via IRSA)', 'iSHELL'): 'R ≈ 80,000 (0.375" slit)',
    ('IRTF Legacy Archive', 'SpeX'): 'R ≈ 200 (prism) – 2,500 (cross-dispersed)',
    ('IRTF Legacy Archive', 'CSHELL'): 'R ≈ 5,000–43,000 (slit-dependent)',
    ('Keck Observatory Archive', 'NIRSPEC'): 'R ≈ 2,000–25,000 (mode-dependent)',
    ('Keck Observatory Archive', 'HIRES'): 'R ≈ 25,000–85,000 (slit-dependent)',
    ('Keck Observatory Archive', 'MOSFIRE'): 'R ≈ 3,600',
    ('Keck Observatory Archive', 'LRIS'): 'R ≈ 300–2,500 (grism/grating-dependent)',
    ('Keck Observatory Archive', 'NIRES'): 'R ≈ 2,700',
    ('Keck Observatory Archive', 'OSIRIS'): 'R ≈ 3,800 (near-IR IFU)',
    ('Keck Observatory Archive', 'DEIMOS'): 'R ≈ 1,000–6,000 (grating-dependent)',
    ('Keck Observatory Archive', 'KPF'): 'R ≈ 98,000 (also 35,000 simultaneous mode)',
    ('Keck Observatory Archive', 'ESI'): 'R ≈ 1,000–8,000 (mode-dependent)',
    ('LAMOST', 'LAMOST'): 'R ≈ 1,800',
    ('LAMOST — MRS', 'LAMOST-MRS'): 'R ≈ 7,500',
    ('LBT — PEPSI', 'MODS'): 'R ≈ 1,000–3,000 (grating-dependent)',
    ('LBT — PEPSI', 'LUCI'): 'R ≈ 4,000–8,000 (mode-dependent)',
    ('LBT — PEPSI', 'PEPSI'): 'R ≈ 43,000–320,000 (mode-dependent)',
    ('Las Cumbres Observatory -- FLOYDS', 'FLOYDS'): 'R ≈ 400–700 (order-dependent)',
    ('Las Cumbres Observatory -- NRES', 'NRES'): 'R ≈ 48,000–53,000',
    ('Lick / Mt. Hamilton (Shane + APF)', 'Lick APF'): 'R ≈ 100,000',
    ('Lick / Mt. Hamilton (Shane + APF)', 'Lick shane'): 'R ≈ 600–2,000 (Kast, grating-dependent)',
    ('MAST', 'LWP'): 'R ≈ 250–300 (low dispersion) or 10,000–15,000 (high dispersion, IUE)',
    ('MAST', 'SWP'): 'R ≈ 250–300 (low dispersion) or 10,000–15,000 (high dispersion, IUE)',
    ('MAST', 'LWR'): 'R ≈ 250–300 (low dispersion) or 10,000–15,000 (high dispersion, IUE — LWP\'s pre-1983 predecessor camera, same optics)',
    ('MAST', 'ASTRO-1 WUPPE'): 'R ≈ 230–530 (~6 Å resolution element, Astro-1 shuttle mission)',
    ('MAST', 'ASTRO-2 WUPPE'): 'R ≈ 230–530 (~6 Å resolution element, Astro-2 shuttle mission)',
    ('MAST', 'BEFS'): 'R ≈ 3,000 (ORFEUS-SPAS)',
    ('MAST', 'TUES'): 'R ≈ 10,000–13,000 (ORFEUS-SPAS echelle)',
    ('MAST', 'FUV'): 'R ≈ 300–620 (~3 Å resolution element, HUT)',
    ('MAST', 'DS/S'): 'R ≈ 200–400 (EUVE Deep Survey/Spectrometer, SW/MW/LW channels combined)',
    ('MAST', 'WFC3/IR'): 'R ≈ 130 (grism mode)',
    ('MAST', 'COS/FUV'): 'R ≈ 2,400–24,000 (grating-dependent)',
    ('MAST', 'STIS/CCD'): 'R ≈ 500–114,000 (mode-dependent)',
    ('MAST', 'NICMOS/NIC3'): 'R ≈ 200 (grism mode)',
    ('MAST', 'HRS/2'): 'R ≈ 2,000–100,000 (grating-dependent, retired GHRS)',
    ('MAST', 'FOS/RD'): 'R ≈ 250–1,300 (grating-dependent, retired)',
    ('MAST', 'STIS/FUV-MAMA'): 'R ≈ 500–114,000 (mode-dependent)',
    ('MAST', 'FOS/BL'): 'R ≈ 250–1,300 (grating-dependent, retired)',
    ('MAST', 'COS/NUV'): 'R ≈ 2,400–24,000 (grating-dependent)',
    ('MAST', 'STIS/NUV-MAMA'): 'R ≈ 500–114,000 (mode-dependent)',
    ('MAST', 'COS'): 'R ≈ 2,400–24,000 (grating-dependent)',
    ('MAST', 'STIS'): 'R ≈ 500–114,000 (mode-dependent)',
    ('MAST', 'WFC3/UVIS'): 'n/a (imaging, no grism)',
    ('MAST', 'ACS/HRC'): 'R ≈ 100 (grism/prism mode, retired)',
    ('MAST', 'HRS/1'): 'R ≈ 2,000–100,000 (grating-dependent, retired GHRS)',
    ('MAST', 'ACS/WFC'): 'R ≈ 100 (grism mode)',
    ('MAST', 'ACS/SBC'): 'R ≈ 100 (grism mode)',
    ('MAST', 'COS-STIS'): '—',
    ('MAST', 'FOC/96'): 'n/a (imaging camera)',
    ('MAST', 'FOC/48'): 'n/a (imaging camera)',
    ('MAST', 'FOC/288'): 'n/a (imaging camera)',
    ('MAST — JWST', 'NIRSPEC/MSA'): 'R ≈ 100–2,700 (mode-dependent)',
    ('MAST — JWST', 'NIRCAM/GRISM'): 'R ≈ 1,600',
    ('MAST — JWST', 'NIRSPEC/SLIT'): 'R ≈ 100–2,700 (mode-dependent)',
    ('MAST — JWST', 'NIRISS/WFSS'): 'R ≈ 150',
    ('MAST — JWST', 'MIRI/SLIT'): 'R ≈ 40–160 (LRS)',
    ('MAST — JWST', 'NIRSPEC'): 'R ≈ 100–2,700 (mode-dependent)',
    ('MAST — JWST', 'MIRI/SLITLESS'): 'R ≈ 40–160 (LRS)',
    ('MAST — JWST', 'NIRCAM/IMAGE'): 'n/a (imaging)',
    ('MAST — JWST', 'NIRCAM/TARGACQ'): 'n/a (target acquisition)',
    ('MAST — JWST', 'MIRI/IMAGE'): 'n/a (imaging)',
    ('MAST — JWST', 'NIRISS/SOSS'): 'R ≈ 700',
    ('NAOJ (Subaru HDS, via JVO)', 'HDS'): 'R ≈ 45,000–160,000 (slit-dependent)',
    ('NAOJ (Subaru MOIRCS, via JVO)', 'MOIRCS'): 'R ≈ 460–3,500 (grism-dependent: zJ_500/HK_500 low-res, LS_J/LS_H/VB_K/VPH-Y moderate-res)',
    ('NEID (WIYN, Kitt Peak)', 'NEID (HR)'): 'R ≈ 110,000 (High Resolution mode)',
    ('NEID (WIYN, Kitt Peak)', 'NEID (HE)'): 'R ≈ 70,000–90,000 (High Efficiency mode)',
    ('NOT (Nordic Optical Telescope) — FIES', 'FIES'): 'R ≈ 25,000–67,000 (fiber-dependent)',
    ('NOIRLab Astro Data Archive', 'goodman'): 'R ≈ 300–4,500 (grating-dependent)',
    ('NOIRLab Astro Data Archive', 'echelle'): 'R ≈ 40,000–45,000 (CTIO echelle)',
    ('NOIRLab Astro Data Archive', 'chiron'): 'R ≈ 28,000–90,000 (mode-dependent)',
    ('NOIRLab Astro Data Archive', 'triplespec'): 'R ≈ 2,700–3,500',
    ('NOIRLab Astro Data Archive', 'sami'): '—',
    ('NOIRLab Astro Data Archive', 'ghts_red'): 'R ≈ 300–4,500 (grating-dependent)',
    ('NOIRLab Astro Data Archive', 'arcoiris'): 'R ≈ 3,500',
    ('NOIRLab Astro Data Archive', 'cosmos'): 'R ≈ 300–3,000 (grating-dependent)',
    ('NOIRLab Astro Data Archive', 'kosmos'): 'R ≈ 500–5,000 (grating-dependent)',
    ('NOIRLab Astro Data Archive', 'ghts_blue'): 'R ≈ 300–4,500 (grating-dependent)',
    ('OIRSA (CfA)', 'Hectospec'): 'R ≈ 1,000–2,500 (grating-dependent)',
    ('OIRSA (CfA)', 'Hectochelle'): 'R ≈ 20,000–40,000 (order-dependent)',
    ('OIRSA (CfA)', 'echelle'): 'R ≈ 25,000–44,000 (FLWO 1.5m echelle)',
    ('OIRSA (CfA)', 'FAST'): 'R ≈ 1,000–4,000 (grating-dependent)',
    ('Ondrejov Observatory (CCD700)', 'COUDE700'): 'R ≈ 13,000 (twice that near Hbeta)',
    ('PolarBase (ESPaDOnS/Narval/SPIRou/HARPSpol spectropolarimetry)', 'ESPaDOnS'): 'R ≈ 65,000 (spectropolarimetric mode)',
    ('PolarBase (ESPaDOnS/Narval/SPIRou/HARPSpol spectropolarimetry)', 'Narval'): 'R ≈ 65,000 (spectropolarimetric mode)',
    ('PolarBase (ESPaDOnS/Narval/SPIRou/HARPSpol spectropolarimetry)', 'neo-Narval'): 'R ≈ 65,000 (spectropolarimetric mode)',
    ('PolarBase (ESPaDOnS/Narval/SPIRou/HARPSpol spectropolarimetry)', 'SPIRou'): 'R ≈ 70,000',
    ('PolarBase (ESPaDOnS/Narval/SPIRou/HARPSpol spectropolarimetry)', 'HARPSpol'): 'R ≈ 115,000',
    ('RAVE', 'RAVE'): 'R ≈ 7,500',
    ('Ritter Observatory (PREST)', 'Ritter Echelle'): 'R ≈ 26,000 (H-alpha region, both CCD camera generations; briefly R ≈ 50,000 in 1997 with a narrower slit)',
    ('Ritter Observatory (PREST)', 'Ritter LDS'): 'R ≈ 1,000–6,000 (grating-dependent; R ≈ 6,000 default)',
    ('SALT HRS (SAAO SSDA)', 'HRS'): 'R ≈ 15,000–65,000 (LR/MR/HR/HS mode)',
    ('SDSS Legacy Optical', 'SDSS/BOSS'): 'R ≈ 1,300–2,600 (wavelength-dependent)',
    ('SDSS-V — APOGEE', 'APOGEE'): 'R ≈ 22,500',
    ('SDSS-V — Optical', 'SDSS-V/BOSS'): 'R ≈ 1,300–2,600 (wavelength-dependent)',
    ('SOPHIE (OHP)', 'SOPHIE'): 'R ≈ 39,000–75,000 (HE/HR mode)',
    ('SVO CAB Stellar Libraries', 'MILES'): 'R ≈ 2,000 (2.50 Å FWHM)',
    ('SVO CAB Stellar Libraries', 'STELIB'): 'R ≈ 2,000 (~3 Å FWHM)',
    ('SVO CAB Stellar Libraries', 'XSL'): 'R ≈ 8,000–11,000 (arm-dependent)',
    ('SVO CAB Stellar Libraries', 'CaT'): 'R ≈ 5,000–6,000 (1.5 Å FWHM)',
    ('SVO CAB Stellar Libraries', 'SpeX Prism Library'): 'R ≈ 75–200',
    ('SVO CAB Stellar Libraries', 'Keck/HIRES (Yee 2017)'): 'R ≈ 60,000',
    ('SVO CAB Stellar Libraries', 'Keck/NIRSPEC (BDSS)'): 'R ≈ 2,000',
    ('SVO CAB Stellar Libraries', 'GAUDI (Elodie)'): 'R ≈ 42,000',
    ('SVO CAB Stellar Libraries', 'GAUDI (FEROS)'): 'R ≈ 48,000',
    ('SVO CAB Stellar Libraries', 'GAUDI (Coralie)'): 'R ≈ 50,000',
    ('SVO CAB Stellar Libraries', 'GAUDI (SARG)'): 'R ≈ 29,000–164,000 (slit-dependent)',
    # X-ray transmission gratings -- resolving power is set by the grating,
    # not the detector recording the dispersed light, so all detector
    # combinations of a given grating share one value. Deliberately absent
    # from INSTRUMENT_WAVELENGTH_RANGE_NM below -- see that dict's own
    # comment on why.
    ('Chandra X-ray Observatory', 'HETG (ACIS-S)'): 'R ≈ 1,000 (High Energy Transmission Grating)',
    ('Chandra X-ray Observatory', 'HETG (ACIS-I)'): 'R ≈ 1,000 (High Energy Transmission Grating)',
    ('Chandra X-ray Observatory', 'HETG (HRC-I)'): 'R ≈ 1,000 (High Energy Transmission Grating)',
    ('Chandra X-ray Observatory', 'LETG (HRC-S)'): 'R ≈ 1,000–2,000 (Low Energy Transmission Grating)',
    ('Chandra X-ray Observatory', 'LETG (ACIS-S)'): 'R ≈ 1,000–2,000 (Low Energy Transmission Grating)',
    ('Chandra X-ray Observatory', 'LETG (ACIS-I)'): 'R ≈ 1,000–2,000 (Low Energy Transmission Grating)',
    ('Chandra X-ray Observatory', 'LETG (HRC-I)'): 'R ≈ 1,000–2,000 (Low Energy Transmission Grating)',
    ('XMM-Newton RGS', 'RGS1'): 'R ≈ 150–800 (first order, wavelength-dependent)',
    ('XMM-Newton RGS', 'RGS2'): 'R ≈ 150–800 (first order, wavelength-dependent)',
}


# Pulls every number out of an INSTRUMENT_RESOLVING_POWER string, e.g.
# "R ≈ 40,000–110,000 (slit-dependent)" -> [40000.0, 110000.0]. Good enough
# for a range-overlap filter, not for display -- the min/max of whatever
# numbers appear, regardless of what qualifier text surrounds them (a
# trailing "100,000+" still contributes 100000.0). This is exactly why the
# webapp.app's advanced-search panel spells out that these are approximate.
_RESOLVING_POWER_NUM_RE = re.compile(r"\d[\d,]*(?:\.\d+)?")


def parse_resolving_power_range(text: str) -> tuple[float, float] | None:
    nums = [float(n.replace(",", "")) for n in _RESOLVING_POWER_NUM_RE.findall(text)]
    return (min(nums), max(nums)) if nums else None
