"""Hand-maintained per-(archive, instrument) published wavelength range, in
nm -- pulled out of webapp.app so scripts/export_to_parquet.py can also read
it (that module can't import webapp.app directly: importing it triggers its
module-level _make_connection(), which needs SPECTRA_DATA_URL/DIR set, see
that module's own comment on STAR_NAME_INDEX_NORMALIZE_SQL). This file has no
side effects and no Flask/DB imports, so both can import it freely.

Same hand-maintained-dict risk flagged in the wavelength-coverage-chart-gaps
audit (webapp.app's INSTRUMENT_RESOLVING_POWER docstring, PR #109): a new
archive/instrument that never gets a key here just silently doesn't render
on the search page's wavelength chart, and now also silently doesn't
contribute to the leaderboard's diversity/coverage metrics
(scripts.export_to_parquet's DIVERSITY_* queries). Re-run that PR's audit
script periodically rather than waiting for another one-star bug report.
"""

from __future__ import annotations

# Published wavelength range in nm (approximate -- taken from each
# instrument's own documentation, at whatever precision that source quotes)
# per (archive display_name, instrument). Powers the /?q=... search page's
# wavelength-coverage chart -- see webapp.app's _wavelength_coverage_bars.
# The chart's x-axis is log-scaled (see 'wavelength-plot' in the page
# template), so X-ray gratings sit fine on the same chart as optical/IR
# instruments, just far to the left of everything else -- Chandra's
# HETG/LETG and XMM-Newton's RGS1/RGS2 are included below for that reason.
# Deliberately a strict subset of webapp.app's INSTRUMENT_RESOLVING_POWER
# keys: n/a (imaging-only) entries are omitted outright, and a handful of
# obscure/retired instruments this project couldn't confirm a real published
# range for (e.g. CFHT's PYTHIAS, HERZBERG, OSIS, PUMA, SISFP, ISIS;
# Gemini's CIRPASS/OSCIR; NOIRLab's sami; ESO's APEXHET, a submm heterodyne
# receiver with no meaningful nm range; HST's COS-STIS combined mode) are
# left out rather than guessed -- a missing key just means that instrument's
# bar doesn't render, the same graceful-degradation shape as
# INSTRUMENT_RESOLVING_POWER's own "—". A few instruments (GALAH/HERMES,
# LAMOST-MRS) are non-contiguous multi-band spectrographs -- the tuple here
# is the outer envelope (first band's blue edge to last band's red edge),
# not literal continuous coverage; the chart doesn't attempt to render the
# internal gap, and scripts.export_to_parquet's diversity-coverage metric
# inherits the same envelope-not-literal-coverage approximation.
INSTRUMENT_WAVELENGTH_RANGE_NM: dict[tuple[str, str], tuple[float, float]] = {
    ('Asiago Observatory (Echelle)', 'Echelle + Andor iKon DW436-BV'): (360, 730),
    ('Asiago Observatory (Echelle)', 'echelle hi-res Spectrograph'): (360, 730),
    ('Asiago Observatory (Echelle)', 'Echelle Hi-Res Spectrograph'): (360, 730),
    ('Asiago Observatory (Echelle)', 'ECHELLE REOSC'): (360, 730),
    ('CARMENES', 'CARMENES VIS'): (520, 960),
    ('CARMENES (CAHA archive, VIS+NIR)', 'CARMENES NIR'): (960, 1710),
    ('CARMENES (CAHA archive, VIS+NIR)', 'CARMENES VIS'): (520, 960),
    ('CFHT / CADC', 'SPIRou'): (980, 2350),
    ('CFHT / CADC', 'ESPaDOnS'): (370, 1050),
    ('CFHT / CADC', 'FTS'): (450, 1100),
    ('CFHT / CADC', 'TIGER'): (400, 700),
    ('CFHT / CADC', 'MOS'): (370, 900),
    ('CFHT / CADC', 'SIS'): (370, 1000),
    ('CFHT / CADC', 'GECKO'): (300, 1000),
    ('Chandra X-ray Observatory', 'HETG (ACIS-S)'): (0.12, 3.1),
    ('Chandra X-ray Observatory', 'HETG (ACIS-I)'): (0.12, 3.1),
    ('Chandra X-ray Observatory', 'HETG (HRC-I)'): (0.12, 3.1),
    ('Chandra X-ray Observatory', 'LETG (HRC-S)'): (0.12, 17.5),
    ('Chandra X-ray Observatory', 'LETG (ACIS-S)'): (0.12, 6.0),
    ('Chandra X-ray Observatory', 'LETG (ACIS-I)'): (0.12, 6.0),
    ('Chandra X-ray Observatory', 'LETG (HRC-I)'): (0.12, 17.5),
    ('DAO (Dominion Astrophysical Observatory)', 'McKellar Spectrograph'): (350, 900),
    ('DAO (Dominion Astrophysical Observatory)', 'Cassegrain Spectrograph'): (350, 900),
    ('DAO (Dominion Astrophysical Observatory)', 'Cassegrain Spectropolarimeter'): (350, 900),
    ('DESI', 'DESI'): (360, 980),
    ('ELODIE (OHP)', 'ELODIE'): (390, 680),
    ('ESO Science Archive', 'GIRAFFE'): (370, 900),
    ('ESO Science Archive', 'HARPS'): (378, 691),
    ('ESO Science Archive', 'XSHOOTER'): (300, 2480),
    ('ESO Science Archive', 'VIMOS'): (360, 1000),
    ('ESO Science Archive', 'FORS2'): (330, 1100),
    ('ESO Science Archive', 'UVES'): (300, 1100),
    ('ESO Science Archive', 'FEROS'): (350, 920),
    ('ESO Science Archive', 'NIRPS'): (980, 1800),
    ('ESO Science Archive', 'ESPRESSO'): (380, 788),
    ('ESO Science Archive', 'EFOSC'): (330, 1100),
    ('ESO Science Archive', 'KMOS'): (800, 2500),
    ('ESO Science Archive', 'CRIRES'): (950, 5300),
    ('ESO Science Archive', 'SOFI'): (950, 2500),
    ('ESO Science Archive', 'FORS1'): (330, 1100),
    ('ESO Science Archive', 'MUSE'): (480, 930),
    ('ESO Science Archive', 'SINFONI'): (1100, 2450),
    ('ESO Archive (Raw)', 'HARPS'): (378, 691),
    ('ESO Archive (Raw)', 'XSHOOTER'): (300, 2480),
    ('ESO Archive (Raw)', 'FORS2'): (330, 1100),
    ('ESO Archive (Raw)', 'FORS1'): (330, 1100),
    ('ESO Archive (Raw)', 'UVES'): (300, 1100),
    ('ESO Archive (Raw)', 'FEROS'): (350, 920),
    ('ESO Archive (Raw)', 'NIRPS'): (980, 1800),
    ('ESO Archive (Raw)', 'ESPRESSO'): (380, 788),
    ('ESO Archive (Raw)', 'EFOSC'): (330, 1100),
    ('ESO Archive (Raw)', 'CRIRES'): (950, 5300),
    ('ESO Archive (Raw)', 'SOFI'): (950, 2500),
    ('FEROS Public Spectra (GAVO)', 'FEROS'): (350, 920),
    ('Flash/Heros Public Spectra (GAVO)', 'Flash/Heros'): (350, 870),
    ('GALAH', 'GALAH (HERMES)'): (471, 789),
    ('GTC (Gran Telescopio CANARIAS)', 'EMIR'): (900, 2500),
    ('GTC (Gran Telescopio CANARIAS)', 'OSIRIS'): (365, 1000),
    ('GTC (Gran Telescopio CANARIAS)', 'MEGARA'): (365, 1000),
    ('GTC (Gran Telescopio CANARIAS)', 'HORuS'): (383, 690),
    ('GTC (Gran Telescopio CANARIAS)', 'CANARICAM'): (8000, 25000),
    ('Gaia RVS', 'Gaia RVS'): (846, 870),
    ('Gemini Observatory Archive', 'GNIRS'): (900, 2500),
    ('Gemini Observatory Archive', 'GMOS-N'): (360, 1000),
    ('Gemini Observatory Archive', 'GMOS-S'): (360, 1000),
    ('Gemini Observatory Archive', 'PHOENIX'): (1000, 5000),
    ('Gemini Observatory Archive', 'GPI'): (900, 2400),
    ('Gemini Observatory Archive', 'NIRI'): (1000, 2500),
    ('Gemini Observatory Archive', 'NIFS'): (940, 2500),
    ('Gemini Observatory Archive', 'F2'): (900, 2500),
    ('Gemini Observatory Archive', 'GRACES'): (500, 1050),
    ('Gemini Observatory Archive', 'MAROON-X'): (500, 920),
    ('Gemini Observatory Archive', 'michelle'): (7900, 25300),
    ('Gemini Observatory Archive', 'TEXES'): (5000, 25000),
    ('Gemini Observatory Archive', 'TReCS'): (8000, 25000),
    ('Gemini Observatory Archive', 'GHOST'): (363, 1000),
    ('Gemini Observatory Archive', 'FLAMINGOS'): (1000, 2500),
    ('Gemini Observatory Archive', 'bHROS'): (350, 1050),
    ('Gemini Observatory Archive — GHOST', 'GHOST'): (363, 1000),
    ('Gemini Observatory Archive — IGRINS', 'IGRINS'): (1450, 2450),
    ('HARPS-N (TNG)', 'HARPS-N'): (383, 693),
    ('HERMES (Mercator Telescope, KU Leuven)', 'HERMES'): (377, 900),
    ('HEROS at Ondrejov', 'HEROS (Ondrejov)'): (350, 870),
    ('HPOL (Wisconsin H-alpha/HPOL spectropolarimeter, STScI)', 'HPOL'): (320, 1050),
    ('IACOB Spectroscopic Database (IAC)', 'MERCATOR'): (377, 900),
    ('IACOB Spectroscopic Database (IAC)', 'NOT'): (370, 830),
    ('ING Archive (WHT/ISIS)', 'WHT/ISIS red arm'): (500, 1000),
    ('ING Archive (WHT/ISIS)', 'WHT/ISIS blue arm'): (300, 550),
    ('ING Archive (WHT/ISIS)', 'WHT/ISIS RED ARM'): (500, 1000),
    ('ING Archive (WHT/ISIS)', 'WHT/ISIS BLUE ARM'): (300, 550),
    ('IRSA Space-Mission Stellar Collections', 'Spitzer/IRS (SASS)'): (5200, 38000),
    ('IRSA Space-Mission Stellar Collections', 'Spitzer/IRS (Std Stars)'): (5200, 38000),
    ('IRSA Space-Mission Stellar Collections', 'ISO/SWS'): (2400, 45200),
    ('IRSA Space-Mission Stellar Collections', 'IRAS/LRS'): (7700, 22600),
    ('IRSA Space-Mission Stellar Collections', 'SOFIA/EXES'): (4500, 28300),
    ('IRSA Space-Mission Stellar Collections', 'IRTF/MEarth'): (700, 5300),
    ('IRTF SpeX (via IRSA)', 'SpeX'): (700, 5300),
    ('IRTF iSHELL (via IRSA)', 'iSHELL'): (1060, 5300),
    ('IRTF Legacy Archive', 'SpeX'): (700, 5300),
    ('IRTF Legacy Archive', 'CSHELL'): (1000, 5500),
    ('Keck Observatory Archive', 'NIRSPEC'): (950, 5500),
    ('Keck Observatory Archive', 'HIRES'): (300, 1000),
    ('Keck Observatory Archive', 'MOSFIRE'): (970, 2450),
    ('Keck Observatory Archive', 'LRIS'): (300, 1100),
    ('Keck Observatory Archive', 'NIRES'): (940, 2450),
    ('Keck Observatory Archive', 'OSIRIS'): (1000, 2400),
    ('Keck Observatory Archive', 'DEIMOS'): (410, 1100),
    ('Keck Observatory Archive', 'KPF'): (445, 870),
    ('Keck Observatory Archive', 'ESI'): (390, 1090),
    ('LAMOST', 'LAMOST'): (370, 900),
    ('LAMOST — MRS', 'LAMOST-MRS'): (495, 685),
    ('LBT — PEPSI', 'MODS'): (320, 1000),
    ('LBT — PEPSI', 'LUCI'): (850, 2500),
    ('LBT — PEPSI', 'PEPSI'): (383, 907),
    ('Las Cumbres Observatory -- FLOYDS', 'FLOYDS'): (320, 1000),
    ('Las Cumbres Observatory -- NRES', 'NRES'): (380, 860),
    ('Lick / Mt. Hamilton (Shane + APF)', 'Lick APF'): (374, 970),
    ('Lick / Mt. Hamilton (Shane + APF)', 'Lick shane'): (330, 1000),
    ('MAST', 'LWP'): (185, 335),
    ('MAST', 'SWP'): (115, 198),
    ('MAST', 'LWR'): (185, 335),
    ('MAST', 'ASTRO-1 WUPPE'): (140, 320),
    ('MAST', 'ASTRO-2 WUPPE'): (140, 320),
    ('MAST', 'BEFS'): (40, 120),
    ('MAST', 'TUES'): (91, 141),
    ('MAST', 'FUV'): (91.2, 185),
    ('MAST', 'DS/S'): (7.0, 76.0),
    ('MAST', 'WFC3/IR'): (800, 1700),
    ('MAST', 'COS/FUV'): (90, 205),
    ('MAST', 'STIS/CCD'): (164, 1030),
    ('MAST', 'NICMOS/NIC3'): (1400, 2500),
    ('MAST', 'HRS/2'): (115, 320),
    ('MAST', 'FOS/RD'): (160, 850),
    ('MAST', 'STIS/FUV-MAMA'): (115, 170),
    ('MAST', 'FOS/BL'): (130, 550),
    ('MAST', 'COS/NUV'): (165, 320),
    ('MAST', 'STIS/NUV-MAMA'): (165, 310),
    ('MAST', 'COS'): (90, 320),
    ('MAST', 'STIS'): (115, 1030),
    ('MAST', 'HRS/1'): (105, 320),
    ('MAST', 'ACS/WFC'): (550, 1050),
    ('MAST', 'ACS/HRC'): (170, 1050),
    ('MAST', 'ACS/SBC'): (115, 180),
    ('MAST — JWST', 'NIRSPEC/MSA'): (600, 5300),
    ('MAST — JWST', 'NIRCAM/GRISM'): (2400, 5000),
    ('MAST — JWST', 'NIRSPEC/SLIT'): (600, 5300),
    ('MAST — JWST', 'NIRISS/WFSS'): (800, 2200),
    ('MAST — JWST', 'MIRI/SLIT'): (5000, 12000),
    ('MAST — JWST', 'NIRSPEC'): (600, 5300),
    ('MAST — JWST', 'MIRI/SLITLESS'): (5000, 12000),
    ('MAST — JWST', 'NIRISS/SOSS'): (600, 2800),
    ('NAOJ (Subaru HDS, via JVO)', 'HDS'): (300, 1000),
    ('NAOJ (Subaru MOIRCS, via JVO)', 'MOIRCS'): (900, 2500),
    ('NEID (WIYN, Kitt Peak)', 'NEID (HR)'): (380, 930),
    ('NEID (WIYN, Kitt Peak)', 'NEID (HE)'): (380, 930),
    ('NOT (Nordic Optical Telescope) — FIES', 'FIES'): (370, 830),
    ('NOIRLab Astro Data Archive', 'goodman'): (320, 900),
    ('NOIRLab Astro Data Archive', 'echelle'): (350, 900),
    ('NOIRLab Astro Data Archive', 'chiron'): (410, 870),
    ('NOIRLab Astro Data Archive', 'triplespec'): (950, 2460),
    ('NOIRLab Astro Data Archive', 'ghts_red'): (500, 900),
    ('NOIRLab Astro Data Archive', 'arcoiris'): (700, 2450),
    ('NOIRLab Astro Data Archive', 'cosmos'): (350, 950),
    ('NOIRLab Astro Data Archive', 'kosmos'): (330, 1000),
    ('NOIRLab Astro Data Archive', 'ghts_blue'): (320, 700),
    ('OIRSA (CfA)', 'Hectospec'): (370, 920),
    ('OIRSA (CfA)', 'Hectochelle'): (500, 900),
    ('OIRSA (CfA)', 'echelle'): (350, 900),
    ('OIRSA (CfA)', 'FAST'): (350, 750),
    ('Ondrejov Observatory (CCD700)', 'COUDE700'): (625, 670),
    ('PolarBase (ESPaDOnS/Narval/SPIRou/HARPSpol spectropolarimetry)', 'ESPaDOnS'): (370, 1050),
    ('PolarBase (ESPaDOnS/Narval/SPIRou/HARPSpol spectropolarimetry)', 'Narval'): (370, 1000),
    ('PolarBase (ESPaDOnS/Narval/SPIRou/HARPSpol spectropolarimetry)', 'neo-Narval'): (370, 1000),
    ('PolarBase (ESPaDOnS/Narval/SPIRou/HARPSpol spectropolarimetry)', 'SPIRou'): (980, 2350),
    ('PolarBase (ESPaDOnS/Narval/SPIRou/HARPSpol spectropolarimetry)', 'HARPSpol'): (378, 691),
    ('RAVE', 'RAVE'): (841, 879),
    ('Ritter Observatory (PREST)', 'Ritter Echelle'): (410, 683),
    ('Ritter Observatory (PREST)', 'Ritter LDS'): (610, 670),
    ('SALT HRS (SAAO SSDA)', 'HRS'): (370, 890),
    ('SDSS Legacy Optical', 'SDSS/BOSS'): (360, 1040),
    ('SDSS-V — APOGEE', 'APOGEE'): (1514, 1696),
    ('SDSS-V — Optical', 'SDSS-V/BOSS'): (360, 1040),
    ('SOPHIE (OHP)', 'SOPHIE'): (387, 694),
    ('SVO CAB Stellar Libraries', 'MILES'): (352.5, 750.0),
    ('SVO CAB Stellar Libraries', 'STELIB'): (320.0, 950.0),
    ('SVO CAB Stellar Libraries', 'XSL'): (300.0, 2480.0),
    ('SVO CAB Stellar Libraries', 'CaT'): (834.8, 882.8),
    ('XMM-Newton RGS', 'RGS1'): (0.5, 3.8),
    ('XMM-Newton RGS', 'RGS2'): (0.5, 3.8),
}
